name: Greeting from TANRuijie
on: push

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Ruijie
        LAST_NAME: TAN
      run:
        echo $MY_VAR $FIRST_NAME $LAST_NAME.

